export interface School {
  value: string;
  labelGR: string;
  labelUK: string;
}

export const schools: School[] = [
  { value: "1", labelGR: "Α ΤΕΣΕΚ Λεμεσού", labelUK: "A TESEK Limassol" },
  { value: "2", labelGR: "ΑΘΗΝΑΪΔΕΙΟ ΓΥΜΝΑΣΙΟ ΚΑΘΟΛΙΚΗΣ", labelUK: "Athenaideio Catholic Gymnasium" },
  { value: "3", labelGR: "Απεήτειο Γυμνάσιο", labelUK: "Apeiteio Gymnasium" },
  { value: "4", labelGR: "Γ΄ ΤΕΣΕΚ ΛΕΜΕΣΟΥ", labelUK: "C TESEK Limassol" },
  { value: "5", labelGR: "Γυμνάσιο Α Αγίου Θεοδώρου Πάφου", labelUK: "A Gymnasium of Saint Theodoros Paphos" },
  { value: "6", labelGR: "Γυμνάσιο Αγίας Βαρβάρας Κ. Πολεμιδιών", labelUK: "Gymnasium of Agia Varvara Kato Polemidia" },
  { value: "7", labelGR: "Γυμνάσιο Αγίας Παρασκευής Γεροσκήπου", labelUK: "Gymnasium of Agia Paraskevi Geroskipou" },
  { value: "8", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΑΣ ΦΥΛΑΞΕΩΣ", labelUK: "Gymnasium of Agia Fylaxeos" },
  { value: "9", labelGR: "Γυμνάσιο Αγίου Αθανασίου", labelUK: "Gymnasium of Agios Athanasios" },
  { value: "10", labelGR: "Γυμνάσιο Αγίου Αντωνίου", labelUK: "Gymnasium of Agios Antonios" },
  { value: "11", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΟΥ ΙΩΑΝΝΗ ΚΑΤΩ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Gymnasium of Agios Ioannis Kato Polemidia" },
  { value: "12", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΟΥ ΝΕΟΦΥΤΟΥ", labelUK: "Gymnasium of Agios Neophytos" },
  { value: "13", labelGR: "ΓΥΜΝΑΣΙΟ ΑΠΟΣΤΟΛΟΥ ΑΝΔΡΕΑ ΕΜΠΑΣ", labelUK: "Apostolos Andreas Gymnasium of Empa" },
  { value: "14", labelGR: "ΓΥΜΝΑΣΙΟ ΑΠΟΣΤΟΛΟΥ ΠΑΥΛΟΥ", labelUK: "Apostle Paul Gymnasium" },
  { value: "15", labelGR: "ΓΥΜΝΑΣΙΟ ΔΡΟΣΙΑΣ", labelUK: "Drosia Gymnasium" },
  { value: "16", labelGR: "ΓΥΜΝΑΣΙΟ ΕΠΙΣΚΟΠΗΣ", labelUK: "Episkopi Gymnasium" },
  { value: "17", labelGR: "ΓΥΜΝΑΣΙΟ ΖΑΚΑΚΙΟΥ", labelUK: "Zakaki Gymnasium" },
  { value: "18", labelGR: "Γυμνάσιο Λύκειο Πολεμίου", labelUK: "Polemi Gymnasium-Lyceum" },
  { value: "19", labelGR: "ΓΥΜΝΑΣΙΟ ΝΕΑΠΟΛΗΣ", labelUK: "Neapolis Gymnasium" },
  { value: "20", labelGR: "ΓΥΜΝΑΣΙΟ ΠΑΝΑΓΙΑΣ ΘΕΟΣΚΕΠΑΣΤΗΣ", labelUK: "Panagia Theoskepasti Gymnasium" },
  { value: "21", labelGR: "Γυμνάσιο Παραλιμνίου", labelUK: "Paralimni Gymnasium" },
  { value: "22", labelGR: "ΓΥΜΝΑΣΙΟ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Polemidia Gymnasium" },
  { value: "23", labelGR: "ΓΥΜΝΑΣΙΟ ΠΟΛΕΩΣ ΧΡΥΣΟΧΟΥΣ", labelUK: "Gymnasium of Polis Chrysochous" },
  { value: "24", labelGR: "ΓΥΜΝΑΣΙΟ ΤΡΑΧΩΝΙΟΥ", labelUK: "Trachoni Gymnasium" },
  { value: "25", labelGR: "ΓΥΜΝΑΣΙΟ ΥΨΩΝΑ", labelUK: "Ypsonas Gymnasium" },
  { value: "26", labelGR: "Γυμνάσιο-Λύκειο Ειρήνης και Ελευθερίας Δερύνειας-Σωτήρας", labelUK: "Gymnasium-Lyceum of Peace & Freedom Deryneia-Sotira" },
  { value: "27", labelGR: "Γυμνασίου Καλογερόπουλου", labelUK: "Kalogeropoulos Gymnasium" },
  { value: "28", labelGR: "Έργα Πληροφορικής", labelUK: "Informatics Projects" },
  { value: "29", labelGR: "ΘΕΚΛΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Thekleio Gymnasium" },
  { value: "30", labelGR: "Λανίτειο Γυμνάσιο", labelUK: "Laniteio Gymnasium" },
  { value: "31", labelGR: "Λανίτειο Λύκειο", labelUK: "Laniteio Lyceum" },
  { value: "32", labelGR: "ΛΥΚΕΙΟ Α΄ ΑΡΧ. ΜΑΚΑΡΙΟΥ Γ΄ ΠΑΦΟΥ", labelUK: "Arch. Makarios III A' Lyceum of Paphos" },
  { value: "33", labelGR: "Λύκειο Αγίας Φυλάξεως", labelUK: "Lyceum of Agia Fylaxeos" },
  { value: "34", labelGR: "Λύκειο Αγίου Αντωνίου", labelUK: "Lyceum of Agios Antonios" },
  { value: "35", labelGR: "Λύκειο Αγίου Νεοφύτου", labelUK: "Lyceum of Agios Neophytos" },
  { value: "36", labelGR: "Λύκειο Αγίου Ιωάννη", labelUK: "Lyceum of Agios Ioannis" },
  { value: "37", labelGR: "Λύκειο Αγίου Νικολάου", labelUK: "Lyceum of Agios Nikolaos" },
  { value: "38", labelGR: "Λύκειο Αγίου Σπυρίδωνα", labelUK: "Lyceum of Agios Spyridonas" },
  { value: "39", labelGR: "Λύκειο Απ. Βαρνάβα", labelUK: "Lyceum of Apostle Barnabas" },
  { value: "40", labelGR: "ΛΥΚΕΙΟ ΑΠ. ΠΕΤΡΟΥ ΚΑΙ ΠΑΥΛΟΥ", labelUK: "Lyceum of Apostles Peter and Paul" },
  { value: "41", labelGR: "ΛΥΚΕΙΟ Γ. ΤΑΛΙΩΤΗ ΓΕΡΟΣΚΗΠΟΥ", labelUK: "Lyceum of G. Taliotis Geroskipou" },
  { value: "42", labelGR: "ΛΥΚΕΙΟ ΚΑΙ ΤΕΣΕΚ ΕΜΠΑΣ", labelUK: "Lyceum & TESEK Empa" },
  { value: "43", labelGR: "ΛΥΚΕΙΟ ΚΑΙ ΤΕΣΕΚ ΠΟΛΗΣ ΧΡΥΣΟΧΟΥΣ", labelUK: "Lyceum & TESEK Polis Chrysochous" },
  { value: "44", labelGR: "Λύκειο Κοκκινοχωρίων", labelUK: "Lyceum of Kokkinokhoria" },
  { value: "45", labelGR: "Λύκειο Κολοσσίου", labelUK: "Lyceum of Kolossi" },
  { value: "46", labelGR: "ΛΥΚΕΙΟ ΚΥΚΚΟΥ", labelUK: "Kykkos Lyceum" },
  { value: "47", labelGR: "Λύκειο Λινόπετρας", labelUK: "Lyceum of Linopetra" },
  { value: "48", labelGR: "Λύκειο Παραλιμνίου", labelUK: "Lyceum of Paralimni" },
  { value: "49", labelGR: "ΛΥΚΕΙΟ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Lyceum of Polemidia" },
  { value: "50", labelGR: "ΝΙΚΟΛΑΪΔΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Nikolaideio Gymnasium" },
  { value: "51", labelGR: "Περιφερειακό Γυμνάσιο και Λύκειο Λευκάρων", labelUK: "Regional Gymnasium and Lyceum of Lefkara" },
  { value: "52", labelGR: "ΣΧΟΛΗ ΟΜΟΔΟΥΣ", labelUK: "Omodos School" },
  { value: "53", labelGR: "ΤΕΣΕΚ ΑΥΓΟΡΟΥ", labelUK: "TESEK Avgorou" },
  { value: "54", labelGR: "ΤΕΣΕΚ ΠΑΦΟΥ", labelUK: "TESEK Paphos" },
  { value: "55", labelGR: "ΤΣΙΡΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Tsireio Gymnasium" }
];
