export interface School {
  value: string;
  labelGR: string;
  labelUK: string;
}

export const schools: School[] = [
  { value: "43", labelGR: "Α ΤΕΣΕΚ Λεμεσού", labelUK: "A TESEK Limassol" },
  { value: "31", labelGR: "ΑΘΗΝΑΪΔΕΙΟ ΓΥΜΝΑΣΙΟ ΚΑΘΟΛΙΚΗΣ", labelUK: "Athenaideio Catholic Gymnasium" },
  { value: "1174", labelGR: "Απεήτειο Γυμνάσιο", labelUK: "Apeiteio Gymnasium" },
  { value: "1144", labelGR: "Γ΄ ΤΕΣΕΚ ΛΕΜΕΣΟΥ", labelUK: "C TESEK Limassol" },
  { value: "1198", labelGR: "Γυμνάσιο Α Αγίου Θεοδώρου Πάφου", labelUK: "A Gymnasium of Saint Theodoros Paphos" },
  { value: "1158", labelGR: "Γυμνάσιο Αγίας Βαρβάρας Κ. Πολεμιδιών", labelUK: "Gymnasium of Agia Varvara Kato Polemidia" },
  { value: "1104", labelGR: "Γυμνάσιο Αγίας Παρασκευής Γεροσκήπου", labelUK: "Gymnasium of Agia Paraskevi Geroskipou" },
  { value: "6", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΑΣ ΦΥΛΑΞΕΩΣ", labelUK: "Gymnasium of Agia Fylaxeos" },
  { value: "1169", labelGR: "Γυμνάσιο Αγίου Αθανασίου", labelUK: "Gymnasium of Agios Athanasios" },
  { value: "1173", labelGR: "Γυμνάσιο Αγίου Αντωνίου", labelUK: "Gymnasium of Agios Antonios" },
  { value: "1153", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΟΥ ΙΩΑΝΝΗ ΚΑΤΩ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Gymnasium of Agios Ioannis Kato Polemidia" },
  { value: "59", labelGR: "ΓΥΜΝΑΣΙΟ ΑΓΙΟΥ ΝΕΟΦΥΤΟΥ", labelUK: "Gymnasium of Agios Neophytos" },
  { value: "1132", labelGR: "ΓΥΜΝΑΣΙΟ ΑΠΟΣΤΟΛΟΥ ΑΝΔΡΕΑ ΕΜΠΑΣ", labelUK: "Apostolos Andreas Gymnasium of Empa" },
  { value: "1142", labelGR: "ΓΥΜΝΑΣΙΟ ΑΠΟΣΤΟΛΟΥ ΠΑΥΛΟΥ", labelUK: "Apostle Paul Gymnasium" },
  { value: "1167", labelGR: "ΓΥΜΝΑΣΙΟ ΔΡΟΣΙΑΣ", labelUK: "Drosia Gymnasium" },
  { value: "19", labelGR: "ΓΥΜΝΑΣΙΟ ΕΠΙΣΚΟΠΗΣ", labelUK: "Episkopi Gymnasium" },
  { value: "1135", labelGR: "ΓΥΜΝΑΣΙΟ ΖΑΚΑΚΙΟΥ", labelUK: "Zakaki Gymnasium" },
  { value: "1072", labelGR: "Γυμνάσιο Λύκειο Πολεμίου", labelUK: "Polemi Gymnasium-Lyceum" },
  { value: "1231", labelGR: "ΓΥΜΝΑΣΙΟ ΝΕΑΠΟΛΗΣ", labelUK: "Neapolis Gymnasium" },
  { value: "1134", labelGR: "ΓΥΜΝΑΣΙΟ ΠΑΝΑΓΙΑΣ ΘΕΟΣΚΕΠΑΣΤΗΣ", labelUK: "Panagia Theoskepasti Gymnasium" },
  { value: "1157", labelGR: "Γυμνάσιο Παραλιμνίου", labelUK: "Paralimni Gymnasium" },
  { value: "28", labelGR: "ΓΥΜΝΑΣΙΟ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Polemidia Gymnasium" },
  { value: "1203", labelGR: "ΓΥΜΝΑΣΙΟ ΠΟΛΕΩΣ ΧΡΥΣΟΧΟΥΣ", labelUK: "Gymnasium of Polis Chrysochous" },
  { value: "16", labelGR: "ΓΥΜΝΑΣΙΟ ΤΡΑΧΩΝΙΟΥ", labelUK: "Trachoni Gymnasium" },
  { value: "50", labelGR: "ΓΥΜΝΑΣΙΟ ΥΨΩΝΑ", labelUK: "Ypsonas Gymnasium" },
  { value: "1261", labelGR: "Γυμνάσιο-Λύκειο Ειρήνης και Ελευθερίας Δερύνειας-Σωτήρας", labelUK: "Gymnasium-Lyceum of Peace & Freedom Deryneia-Sotira" },
  { value: "1133", labelGR: "Γυμνασίου Καλογερόπουλου", labelUK: "Kalogeropoulos Gymnasium" },
  { value: "1171", labelGR: "Έργα Πληροφορικής", labelUK: "Informatics Projects" },
  { value: "1151", labelGR: "ΘΕΚΛΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Thekleio Gymnasium" },
  { value: "1179", labelGR: "Λανίτειο Γυμνάσιο", labelUK: "Laniteio Gymnasium" },
  { value: "2", labelGR: "Λανίτειο Λύκειο", labelUK: "Laniteio Lyceum" },
  { value: "55", labelGR: "ΛΥΚΕΙΟ Α΄ ΑΡΧ. ΜΑΚΑΡΙΟΥ Γ΄ ΠΑΦΟΥ", labelUK: "Arch. Makarios III A' Lyceum of Paphos" },
  { value: "18", labelGR: "Λύκειο Αγίας Φυλάξεως", labelUK: "Lyceum of Agia Fylaxeos" },
  { value: "14", labelGR: "Λύκειο Αγίου Αντωνίου", labelUK: "Lyceum of Agios Antonios" },
  { value: "1147", labelGR: "Λύκειο Αγίου Νεοφύτου", labelUK: "Lyceum of Agios Neophytos" },
  { value: "11", labelGR: "Λύκειο Αγίου Ιωάννη", labelUK: "Lyceum of Agios Ioannis" },
  { value: "38", labelGR: "Λύκειο Αγίου Νικολάου", labelUK: "Lyceum of Agios Nikolaos" },
  { value: "5", labelGR: "Λύκειο Αγίου Σπυρίδωνα", labelUK: "Lyceum of Agios Spyridonas" },
  { value: "10", labelGR: "Λύκειο Απ. Βαρνάβα", labelUK: "Lyceum of Apostle Barnabas" },
  { value: "1", labelGR: "ΛΥΚΕΙΟ ΑΠ. ΠΕΤΡΟΥ ΚΑΙ ΠΑΥΛΟΥ", labelUK: "Lyceum of Apostles Peter and Paul" },
  { value: "1148", labelGR: "ΛΥΚΕΙΟ Γ. ΤΑΛΙΩΤΗ ΓΕΡΟΣΚΗΠΟΥ", labelUK: "Lyceum of G. Taliotis Geroskipou" },
  { value: "37", labelGR: "ΛΥΚΕΙΟ ΚΑΙ ΤΕΣΕΚ ΕΜΠΑΣ", labelUK: "Lyceum & TESEK Empa" },
  { value: "1152", labelGR: "ΛΥΚΕΙΟ ΚΑΙ ΤΕΣΕΚ ΠΟΛΗΣ ΧΡΥΣΟΧΟΥΣ", labelUK: "Lyceum & TESEK Polis Chrysochous" },
  { value: "1232", labelGR: "Λύκειο Κοκκινοχωρίων", labelUK: "Lyceum of Kokkinokhoria" },
  { value: "1129", labelGR: "Λύκειο Κολοσσίου", labelUK: "Lyceum of Kolossi" },
  { value: "1119", labelGR: "ΛΥΚΕΙΟ ΚΥΚΚΟΥ", labelUK: "Kykkos Lyceum" },
  { value: "1109", labelGR: "Λύκειο Λινόπετρας", labelUK: "Lyceum of Linopetra" },
  { value: "62", labelGR: "Λύκειο Παραλιμνίου", labelUK: "Lyceum of Paralimni" },
  { value: "24", labelGR: "ΛΥΚΕΙΟ ΠΟΛΕΜΙΔΙΩΝ", labelUK: "Lyceum of Polemidia" },
  { value: "1202", labelGR: "ΝΙΚΟΛΑΪΔΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Nikolaideio Gymnasium" },
  { value: "1118", labelGR: "Περιφερειακό Γυμνάσιο και Λύκειο Λευκάρων", labelUK: "Regional Gymnasium and Lyceum of Lefkara" },
  { value: "29", labelGR: "ΣΧΟΛΗ ΟΜΟΔΟΥΣ", labelUK: "Omodos School" },
  { value: "1170", labelGR: "ΤΕΣΕΚ ΑΥΓΟΡΟΥ", labelUK: "TESEK Avgorou" },
  { value: "1071", labelGR: "ΤΕΣΕΚ ΠΑΦΟΥ", labelUK: "TESEK Paphos" },
  { value: "33", labelGR: "ΤΣΙΡΕΙΟ ΓΥΜΝΑΣΙΟ", labelUK: "Tsireio Gymnasium" }
];
